# Generated by Django 2.1.7 on 2019-03-25 10:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptocoin',
            name='wallet',
        ),
        migrations.AddField(
            model_name='wallet',
            name='wallet',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='CryptoCoin',
        ),
    ]
