# Generated by Django 2.1.7 on 2019-03-27 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_news', '0003_auto_20190327_1031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Latest',
        ),
    ]
