# Generated by Django 2.1.7 on 2019-03-27 15:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_news', '0004_delete_latest'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prices', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('news', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
    ]
