# Generated by Django 2.1.7 on 2019-03-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_news', '0005_latestapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestapi',
            name='errorNews',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='latestapi',
            name='errorPrices',
            field=models.BooleanField(default=False),
        ),
    ]
