# Generated by Django 2.1.7 on 2019-03-27 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_news', '0006_auto_20190327_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestapi',
            name='lastUpdate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
